[project]
name = "drgpu"
version = "1.0.0"
description = "DrGPU is a top-down profile analysis tool for GPU kernels"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.0",
    "graphviz>=0.20",
    "pandas-stubs>=2.3.0",
]
